version: '3.0'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
      - ./logs/nginx:/var/log/nginx
    networks:
      - frontend

  php:
    image: php-base
    build:
      context: docker
      dockerfile: php
    depends_on:
      - mysql
    volumes:
      #- docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./www/:/var/www/html/
    networks:
      - frontend

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - frontend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - frontend


networks:
  frontend:
    name: frontend
    driver: bridge